import type { Donor, FollowUpStatus, PaymentStatus } from "@/types/donor";

export { getDashboardMetrics, getDonorMetrics } from "@/lib/metrics";
export type { DashboardMetrics, DonorMetrics } from "@/lib/metrics";
export { buildDonorMessage, formatCurrency } from "@/lib/messages";
export { getDonorRisk, getPriority, getRiskFlags, getRiskReasons, sortDonorsByPriority } from "@/lib/risk";
export type { DonorRisk, DonorRiskFlags } from "@/lib/risk";
export { buildWaLink, buildWhatsAppLink } from "@/lib/whatsapp";

export const donorsSeed: Donor[] = [
  {
    id: "maria-gomez",
    name: "María Gómez",
    phone: "+5491155554444",
    monthlyAmount: 5000,
    paymentStatus: "failed",
    lastPaymentDate: "2026-05-30",
    lastAmountUpdateDate: "2026-03-01",
    lastImpactContactDate: "2026-03-03",
    cause: "Salud comunitaria",
    impactText: "acompañamos a 38 familias con controles de salud",
    followUpStatus: "pending",
  },
  {
    id: "laura-martinez",
    name: "Laura Martínez",
    phone: "+5491163214987",
    monthlyAmount: 8000,
    paymentStatus: "failed",
    lastPaymentDate: "2026-05-25",
    lastAmountUpdateDate: "2026-02-15",
    lastImpactContactDate: "2026-04-27",
    cause: "Becas educativas",
    impactText: "12 estudiantes sostuvieron su escolaridad",
    followUpStatus: "pending",
  },
  {
    id: "valentina-torres",
    name: "Valentina Torres",
    phone: "+5491144087632",
    monthlyAmount: 12000,
    paymentStatus: "failed",
    lastPaymentDate: "2026-06-01",
    lastAmountUpdateDate: "2026-01-10",
    lastImpactContactDate: "2026-02-16",
    cause: "Primera infancia",
    impactText: "24 niñas y niños accedieron a espacios de cuidado",
    followUpStatus: "contacted",
  },
  {
    id: "florencia-herrera",
    name: "Florencia Herrera",
    phone: "+5491139042255",
    monthlyAmount: 9500,
    paymentStatus: "failed",
    lastPaymentDate: "2026-05-19",
    lastAmountUpdateDate: "2025-12-20",
    lastImpactContactDate: "2026-03-10",
    cause: "Seguridad alimentaria",
    impactText: "86 viandas nutritivas llegaron a familias del barrio",
    followUpStatus: "needs_follow_up",
  },
  {
    id: "carlos-rodriguez",
    name: "Carlos Rodríguez",
    phone: "+5491169801142",
    monthlyAmount: 3500,
    paymentStatus: "paid",
    lastPaymentDate: "2026-05-07",
    lastAmountUpdateDate: "2026-03-01",
    lastImpactContactDate: "2026-03-23",
    cause: "Inclusión laboral",
    impactText: "9 personas completaron talleres de formación laboral",
    followUpStatus: "pending",
  },
  {
    id: "sebastian-lopez",
    name: "Sebastián López",
    phone: "+5491152078841",
    monthlyAmount: 2000,
    paymentStatus: "paid",
    lastPaymentDate: "2026-05-09",
    lastAmountUpdateDate: "2025-11-15",
    lastImpactContactDate: "2026-05-17",
    cause: "Apoyo escolar",
    impactText: "31 chicos participaron de tutorías semanales",
    followUpStatus: "pending",
  },
  {
    id: "camila-ruiz",
    name: "Camila Ruiz",
    phone: "+5491160027134",
    monthlyAmount: 6000,
    paymentStatus: "pending",
    lastPaymentDate: "2026-05-02",
    lastAmountUpdateDate: "2026-01-20",
    lastImpactContactDate: "2026-04-02",
    cause: "Hábitat",
    impactText: "7 hogares mejoraron sus condiciones de habitabilidad",
    followUpStatus: "pending",
  },
  {
    id: "nicolas-castro",
    name: "Nicolás Castro",
    phone: "+5491140176683",
    monthlyAmount: 2500,
    paymentStatus: "paid",
    lastPaymentDate: "2026-05-15",
    lastAmountUpdateDate: "2026-03-15",
    lastImpactContactDate: "2026-04-12",
    cause: "Ambiente",
    impactText: "120 árboles nativos fueron plantados y cuidados",
    followUpStatus: "pending",
  },
  {
    id: "diego-fernandez",
    name: "Diego Fernández",
    phone: "+5491164489012",
    monthlyAmount: 1500,
    paymentStatus: "paid",
    lastPaymentDate: "2026-05-22",
    lastAmountUpdateDate: "2026-04-10",
    lastImpactContactDate: "2026-05-07",
    cause: "Adultos mayores",
    impactText: "18 personas mayores participaron de encuentros comunitarios",
    followUpStatus: "pending",
  },
  {
    id: "matias-sanchez",
    name: "Matías Sánchez",
    phone: "+5491158820931",
    monthlyAmount: 4000,
    paymentStatus: "paid",
    lastPaymentDate: "2026-05-17",
    lastAmountUpdateDate: "2026-02-20",
    lastImpactContactDate: "2026-05-12",
    cause: "Deporte social",
    impactText: "45 jóvenes sostuvieron actividades deportivas semanales",
    followUpStatus: "pending",
  },
];

export const demoDonors = donorsSeed;

export const paymentStatusLabels: Record<PaymentStatus, string> = {
  paid: "Pagado",
  failed: "Rechazado",
  pending: "Pendiente",
  unknown: "Desconocido",
};

export const followUpStatusLabels: Record<FollowUpStatus, string> = {
  pending: "Pendiente",
  contacted: "Contactado",
  recovered: "Recuperado",
  wants_increase: "Quiere aumentar",
  needs_follow_up: "Requiere seguimiento",
  cancelled: "Baja",
};
